### PR TITLE
Port swift specific compiler-rt code to Windows

### PR DESCRIPTION
**Pull request by hughbe**
Introduced in 2cf73dc0fd684e3127e0ec9f3f8c432ae8ce7022

@vedantk

### CODE REVIEW

**Review by vedantk — CHANGES_REQUESTED** [review]
Please define a portable helper function in InstrProfilingUtil.{c,h} that can install a signal handler and issue a warning if it isn't successful. It'd be nice to use the 'lprof' prefix for consistency with the other helper functions in that file.

**Comment by hughbe** [comment]
Thanks - I've pushed an update for this. I'll just trigger tests to make sure I haven't broken non-Windows platforms.

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci please smoke test

**Review by vedantk — APPROVED** [review]

**Comment by vedantk** [comment]
LGTM.

**Comment by hughbe** [comment]
@swift-ci Please smoke test

**Comment by hughbe** [comment]
I guess testing doesn't work here... @shahmishal?

**Comment by vedantk** [comment]
Ah, that's right. swift-{llvm, clang, compiler-rt} are not gated. Please run the 'check-profile' target on your dev machine and commit.

**Comment by shahmishal** [comment]
@hughbe Only regular test works on here. 

@swift-ci Please test

**Comment by hughbe** [comment]
Looks like that doesn't do anything?

**Comment by hughbe** [comment]
I've verified that this builds successfully on non-Windows platforms

**Comment by hughbe** [comment]
@swift-ci please test

**Comment by hughbe** [comment]
@swift-ci Please test

**Comment by hughbe** [comment]
@shahmishal please test doesn't work here

**Comment by vedantk** [comment]
@hughbe Would you like me to commit this for you?

**Comment by hughbe** [comment]
Sure, thanks!

**Comment by vedantk** [comment]
commit ac64ee693098615eaeceb290bc59a83f4455b167 (HEAD -> upstream-with-swift, origin/upstream-with-swift, origin/HEAD)
Author: Hugh Bellamy <hughbellars@gmail.com>
Date:   Sat Jan 28 07:30:15 2017

    Port swift specific compiler-rt code to Windows

    https://github.com/apple/swift-compiler-rt/pull/5

**Pull request closed without merging**
