### PR TITLE
Add s390x to ALL_FUZZER_SUPPORTED_ARCH

### PR DESCRIPTION
**Pull request by rposts**
This commit will partially enable support of Fuzzer testcases on s390x

### CODE REVIEW

**Comment by jrose-apple** [comment]
Administrative note: The `stable` branch is a "dead end" of sorts; you'll want to put this into `upstream-with-swift` first and then cherry-pick it to the `swift-5.0-branch` for the next release. (You can read more about the Swift project branches in [swift/docs/Branches.md](https://github.com/apple/swift/blob/master/docs/Branches.md).)

**Comment by cheshire** [comment]
@rposts sorry for the delay. The commit makes sense, but as @jrose-apple says, it should not go into the "stable" branch.
In fact, the commit does not seem to be specific to Swift: could you post it on reviews.llvm.org and add me, kcc, and morehouse as reviewers?

**Comment by cheshire** [comment]
If the commit goes to upstream compiler-rt, it will then be auto-merged into upstream-with-swift.
If you need it for Swift 5.0 specifically, you would also need to cherry-pick it into swift-5.0-branch.

**Review by cheshire — CHANGES_REQUESTED** [review]
This change should probably go to upstream compiler-rt.

**Comment by rposts** [comment]
@cheshire - sorry for the delay.  Holidays and sorts.  I will post it on reviews.llvm.org and cc. folks mentioned.

**Comment by rposts** [comment]
Closing PR until compiler-rt has Fuzzer support enabled on s390x

**Pull request closed without merging**
