### PR TITLE
Propose fix some typos

### PR DESCRIPTION
**Pull request by jeis2497052**
are these updates OK?

### CODE REVIEW

**Comment by jrose-apple** [comment]
Thanks! These fixes should go to the original compiler-rt, though – see http://compiler-rt.llvm.org.

**Comment by jeis2497052** [comment]
OK, so an additional pull request to llvm.org original source of compiler-rt ?

**Comment by jrose-apple** [comment]
Yes please!

**Comment by jrose-apple** [comment]
The Swift project will then pick up your fixes at some point in the future, when we roll forward to a newer version of LLVM, Clang, and compiler-rt.

**Comment by jeis2497052** [comment]
sounds good, looks like LLVM is stuck in subversion :-(

**Comment by delcypher** [comment]
@jeis2497052 You can use git-svn. See http://llvm.org/docs/GettingStarted.html#for-developers-to-work-with-git-svn .

Please also take a look at http://llvm.org/docs/Phabricator.html . That document explains how how to use phabriactor which is what LLVM (and its sub-projects) uses for code review.

**Pull request closed without merging**
